### ISSUE TITLE
Contact form doesn't work with cache enabled

### ISSUE THREAD

**Issue by 01Kuzma** [rblinde/grav-plugin-html-minifier#2]
Hello!
I've tested this plugin on dev server, so can't give much debug information right now.
Once I've set these options: 
`Store minified HTML in cache - Enabled`
`Compression Mode - Smallest`

The modular contact form with dropdown.js failed to submit data. A blank screen appears and I've got these data in the console:

```
Uncaught TypeError: $(...)[0] is undefined
    success https://website.com/assets/670f114de31a2a7701d00dccfb97fccf.js:94
    c https://website.com/assets/7a95dda8545cddd27ab1efd0eebbd80b.js:2
    fireWith https://website.com/assets/7a95dda8545cddd27ab1efd0eebbd80b.js:2
    l https://website.com/assets/7a95dda8545cddd27ab1efd0eebbd80b.js:2
    o https://website.com/assets/7a95dda8545cddd27ab1efd0eebbd80b.js:2
    send https://website.com/assets/7a95dda8545cddd27ab1efd0eebbd80b.js:2
    ajax https://website.com/assets/7a95dda8545cddd27ab1efd0eebbd80b.js:2
    submitHandler https://website.com/assets/670f114de31a2a7701d00dccfb97fccf.js:94
    d https://website.com/assets/670f114de31a2a7701d00dccfb97fccf.js:68
    validate https://website.com/assets/670f114de31a2a7701d00dccfb97fccf.js:68
    dispatch https://website.com/assets/7a95dda8545cddd27ab1efd0eebbd80b.js:2
    handle https://website.com/assets/7a95dda8545cddd27ab1efd0eebbd80b.js:2
[670f114de31a2a7701d00dccfb97fccf.js:94:1180](https://website.com/assets/670f114de31a2a7701d00dccfb97fccf.js)
div with id: #undefined not found
```

Then I've just disabled the `Store minified HTML in cache` and it started to work

**Comment by rblinde** [comment]
Hi!

Storing forms is not a good idea with Grav. Grav adds a unique identifier to the form. When this is cached, a form can only be sent once across all visitors.

You can disable the cache setting on a per-page basis, like so:

```yaml
---
html-minifier:
  cache: false
---
```

I will look more into the specifics later, I'll keep you updated.

**Comment by 01Kuzma** [comment]
Hi!
Thank you very much for the information!
I did try mentioned code, but for some reason the situation is the same :)
OK, will wait for further updates

**Comment by rblinde** [comment]
Did you disable the cache on the modular page or the page including the modular page?

**Comment by 01Kuzma** [comment]
The cache is disabled on the modular page.
I forgot to clear the main cache. Now it's working. Thank you!

**Comment by 01Kuzma** [comment]
But after the form submission on Ctrl+F5 I receive a white page with thank you message :)

**Comment by rblinde** [comment]
I have looked into both normal and modular forms, both seem to be working fine. Can you share some code on how you set up the forms?

**Comment by 01Kuzma** [comment]
Hi, sure, here is mine shortened version:

```
visible: true
cache_enable: false
html-minifier:
    cache: false
form:
    name: contact-form
    template: form-messages
    refresh_prevention: true
    fields:
        -
            name: email            
            type: email
        -
            name: my-file
            type: file
            destination: user/data/files
            accept:
                - application/pdf
        -
            name: telephone
            type: tel
            validate:
                required: true
        -
            name: message
            type: textarea
            rows: null
    buttons:
        -
            type: submit
            value: Submit
    process:
        -
            email:
                from:
                    - '{{ form.value.email|e }}'
                to:
                    - '{{ config.plugins.email.to }}'
                subject: '[Message from] {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
                attachments:
                    - my-file
        -
            message: 'Thank you message'
```
